name: Update Gradle Wrapper
on:
  schedule:
    - cron: '0 0 * * MON'
jobs:
  update-wrapper:
    if: github.repository == 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update Gradle Wrapper"
        id: update
        run: |
          latest=`curl -s https://services.gradle.org/versions/current | jq -cr ".version"`
          echo ::set-output name=latest_version::${latest}
          ./gradlew wrapper --gradle-version $latest
      - uses: gradle/wrapper-validation-action@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upgrade Gradle Wrapper to ${{ steps.update.outputs.latest_version }}
          commit_user_name: micronaut-build
          commit_user_email: micronaut-build@users.noreply.github.com